apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  labels:
    type: storage1
    app: rabbitmq1   
spec:
  claimRef:
    namespace: default
    name: pvc1
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: "/etc/rabbitmq"
  storageClassName: manual
