apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    type: storage1
    app: rabbitmq1
  name: pvc1
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
